# Configuration for chart-releaser-action
# See: https://github.com/helm/chart-releaser

owner: evanjarrett
git-repo: hsm-secrets-operator
charts-dir: helm
target-branch: main
pages-branch: gh-pages
pages-index-path: .
release-name-template: "{{ .Name }}-{{ .Version }}"
commit-username: "$GITHUB_ACTOR"
commit-email: "$GITHUB_ACTOR@users.noreply.github.com"

# Package configuration
package-path: .cr-release-packages
index-path: .
pages-url: https://evanjarrett.github.io/hsm-secrets-operator/

# GitHub release configuration
generate-release-notes: true
make-release-latest: true

# Skip existing releases
skip-existing: true

# Charts to exclude from release (if any)
# exclude-charts:
#   - example-chart