apiVersion: v1
kind: Pod
metadata:
  name: test-coordination
  namespace: secrets
spec:
  containers:
  - name: test
    image: curlimages/curl:latest
    command: ["sleep", "300"]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  restartPolicy: Never
---
apiVersion: hsm.j5t.io/v1alpha1
kind: HSMDevice
metadata:
  name: test-coordination
  namespace: secrets
spec:
  deviceType: "PicoHSM"
  discovery:
    autoDiscovery: true