---
# Primary HSM Device with Mirroring Configuration
apiVersion: hsm.j5t.io/v1alpha1
kind: HSMDevice
metadata:
  name: hsm-primary
  namespace: default
  labels:
    role: primary
    environment: production
    ha.enabled: "true"
spec:
  deviceType: PicoHSM
  
  # USB discovery for Pico HSM
  usb:
    vendorId: "20a0"
    productId: "4230"
  
  # Deploy on nodes with HSM hardware
  nodeSelector:
    hsm.j5t.io/hardware: "available"
    kubernetes.io/arch: "amd64"
  
  # PKCS#11 library configuration
  pkcs11LibraryPath: "/usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so"
  
  # Maximum devices to discover
  maxDevices: 3
  
  # High Availability Mirroring Configuration
  mirroring:
    # Enable readonly mirroring
    policy: "ReadOnly"
    
    # Sync every 5 minutes
    syncInterval: 300
    
    # Enable automatic failover
    autoFailover: true
    
    # Preferred primary node (optional)
    primaryNode: "worker-1"
    
    # Target nodes for mirroring (empty = all available nodes)
    targetNodes:
      - "worker-2"
      - "worker-3"

---
# Service Monitor for Prometheus (if using)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hsm-device-metrics
  namespace: default
  labels:
    app: hsm-secrets-operator
spec:
  selector:
    matchLabels:
      app: hsm-secrets-operator
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
# Pod Disruption Budget for HSM operator
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hsm-operator-pdb
  namespace: hsm-secrets-operator-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: controller-manager

---
# Network Policy for HSM Communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hsm-operator-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: hsm-secrets-operator
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: hsm-client
    ports:
    - protocol: TCP
      port: 8090  # API port
  egress:
  - to: []  # Allow all egress for HSM communication
    ports:
    - protocol: TCP
    - protocol: UDP

---
# Example HSM Secret with HA consideration
apiVersion: hsm.j5t.io/v1alpha1
kind: HSMSecret
metadata:
  name: ha-database-credentials
  namespace: default
  labels:
    app: myapp
    criticality: high
    ha.enabled: "true"
  annotations:
    hsm.j5t.io/description: "HA database credentials with mirroring support"
spec:
  hsmPath: "secrets/ha/database-credentials"
  secretName: "ha-database-credentials"
  
  # Enable auto-sync for HA
  autoSync: true
  
  # More frequent sync for critical secrets
  syncInterval: 180  # 3 minutes
  
  secretType: Opaque

---
# Deployment using HA secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-database-app
  namespace: default
spec:
  replicas: 3  # Multiple replicas for HA
  selector:
    matchLabels:
      app: ha-database-app
  template:
    metadata:
      labels:
        app: ha-database-app
    spec:
      # Spread across nodes for HA
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ha-database-app
              topologyKey: kubernetes.io/hostname
      
      containers:
      - name: app
        image: postgres:13-alpine
        env:
        # Use HA-backed secrets
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: ha-database-credentials
              key: database_name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ha-database-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ha-database-credentials
              key: password
        
        # Health checks for HA
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi