apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: hsm-secrets-operator
    app.kubernetes.io/managed-by: kustomize
    control-plane: controller-manager
  name: hsm-secrets-operator-api
  namespace: system
spec:
  ports:
  - name: api
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    control-plane: controller-manager