{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hsm-secrets-operator.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hsm-secrets-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/part-of: hsm-secrets-operator
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "hsm-secrets-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}

{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hsm-secrets-operator.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hsm-secrets-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: hsm-secrets-operator
spec:
  ports:
  - name: api
    port: {{ .Values.api.port }}
    protocol: TCP
    targetPort: {{ .Values.api.port }}
  selector:
    {{- include "hsm-secrets-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}

{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hsm-secrets-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hsm-secrets-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: hsm-secrets-operator
spec:
  ports:
  - name: webhook
    port: {{ .Values.webhook.port }}
    protocol: TCP
    targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "hsm-secrets-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}