---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hsm.j5t.io
  resources:
  - hsmdevices
  - hsmsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hsm.j5t.io
  resources:
  - hsmdevices/finalizers
  - hsmsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - hsm.j5t.io
  resources:
  - hsmdevices/status
  - hsmsecrets/status
  verbs:
  - get
  - patch
  - update
