---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hsm.j5t.io
  resources:
  - hsmdevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hsm.j5t.io
  resources:
  - hsmpools
  - hsmsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hsm.j5t.io
  resources:
  - hsmpools/finalizers
  - hsmsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - hsm.j5t.io
  resources:
  - hsmpools/status
  - hsmsecrets/status
  verbs:
  - get
  - patch
  - update
