# Default values for hsm-secrets-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Operator image configuration
image:
  repository: hsm-secrets-operator
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to the chart appVersion

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Controller manager configuration
controllerManager:
  # Number of replicas for the controller manager
  replicas: 1
  
  # Resource limits and requests
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  
  # Security context for the controller container
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - "ALL"
  
  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    # runAsUser: 1001

# Service account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# RBAC configuration
rbac:
  # Specifies whether RBAC resources should be created
  create: true

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}

# Node selector for controller pods
nodeSelector: {}

# Tolerations for controller pods
tolerations: []

# Affinity for controller pods
affinity: {}

# HSM configuration
hsm:
  # HSM client type: "mock" for testing, "pkcs11" for production
  clientType: "mock"
  
  # PKCS#11 library configuration (used when clientType is "pkcs11")
  pkcs11:
    # Path to the PKCS#11 library
    library: "/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so"
    # HSM slot ID
    slotId: 0
    # HSM PIN (should be provided via secret)
    pinSecret:
      name: "hsm-pin"
      key: "pin"

# Device discovery configuration
discovery:
  # Enable device discovery (DaemonSet)
  enabled: true
  
  # USB device discovery
  usb:
    enabled: true
    # Well-known HSM device types to discover
    deviceTypes:
      - "pico-hsm"
      - "smartcard-hsm"
  
  # Path-based device discovery
  path:
    enabled: true
    patterns:
      - "/dev/ttyUSB*"
      - "/dev/hidraw*"

# API server configuration
api:
  # Enable the REST API server
  enabled: true
  # Port for the API server
  port: 8080
  # Enable metrics endpoint
  metrics:
    enabled: true
    port: 8443

# Metrics configuration
metrics:
  # Enable metrics collection
  enabled: true
  # Service monitor for Prometheus
  serviceMonitor:
    enabled: false
    namespace: ""
    labels: {}

# Webhook configuration
webhook:
  # Enable admission webhooks
  enabled: true
  port: 9443
  
  # Certificate configuration
  certManager:
    enabled: false
    
  # Certificate Secret (when certManager is disabled)
  # You need to provide your own certificates
  secret:
    name: webhook-server-certs

# Health check configuration
health:
  # Health check probe port
  port: 8081

# Leader election configuration
leaderElection:
  enabled: true

# Custom Resource Definitions
crds:
  # Install CRDs as part of the chart
  install: true
  # Keep CRDs when the chart is uninstalled
  keep: true

# Examples and samples
examples:
  # Create sample HSMSecret resources
  hsmsecret:
    enabled: false
    samples:
      - name: "example-secret"
        namespace: "default"
        hsmPath: "secrets/examples/example-secret"
        syncInterval: 300
  
  # Create sample HSMDevice resources  
  hsmdevice:
    enabled: false
    samples:
      - name: "pico-hsm-discovery"
        namespace: "default"
        deviceType: "pico-hsm"

# Additional configuration
config:
  # Default sync interval for HSMSecrets (seconds)
  defaultSyncInterval: 300
  # Default secret type for created Kubernetes secrets
  defaultSecretType: "Opaque"
  # Enable verbose logging
  verboseLogging: false