apiVersion: hsm.j5t.io/v1alpha1
kind: HSMDevice
metadata:
  labels:
    app.kubernetes.io/name: hsm-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: pico-hsm-discovery
  namespace: default
spec:
  # Device type - automatically uses well-known USB specs
  deviceType: PicoHSM
  
  # Auto-discovery will use built-in USB specifications
  # For Pico HSM: vendorId: "20a0", productId: "4230"
  
  # Optional: Override USB specification
  # usb:
  #   vendorId: "20a0"
  #   productId: "4230"
  #   serialNumber: "PICO123456"  # Optional: target specific device
  
  # Optional: Path-based discovery instead of USB
  # devicePath:
  #   path: "/dev/ttyUSB*"
  #   permissions: "rw"
  
  # Optional: Node selector to limit discovery to specific nodes
  # nodeSelector:
  #   kubernetes.io/hostname: "worker-node-1"
  
  # Optional: PKCS#11 library path
  pkcs11LibraryPath: "/usr/local/lib/libsc-hsm-pkcs11.so"
  
  # Maximum number of devices to discover (default: 10)
  maxDevices: 5
---
apiVersion: hsm.j5t.io/v1alpha1
kind: HSMDevice
metadata:
  name: smartcard-hsm-discovery
  namespace: default
spec:
  deviceType: SmartCardHSM
  
  # Use custom USB specification
  usb:
    vendorId: "04e6"
    productId: "5816"
  
  pkcs11LibraryPath: "/usr/lib/opensc-pkcs11.so"
  maxDevices: 3
---
apiVersion: hsm.j5t.io/v1alpha1
kind: HSMDevice
metadata:
  name: generic-hsm-path-discovery
  namespace: default
spec:
  deviceType: Generic
  
  # Use path-based discovery
  devicePath:
    path: "/dev/sc-hsm*"
    permissions: "rw"
  
  pkcs11LibraryPath: "/usr/lib/generic-pkcs11.so"
  maxDevices: 10
