apiVersion: hsm.j5t.io/v1alpha1
kind: HSMDevice
metadata:
  labels:
    app.kubernetes.io/name: hsm-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: pico-hsm-discovery
  namespace: default
spec:
  # Device type - automatically uses well-known USB specs
  deviceType: PicoHSM
  
  # Discovery configuration (choose one method)
  discovery:
    # Option 1: USB discovery (recommended for Pico HSM)
    usb:
      vendorId: "20a0"
      productId: "4230"
      # serialNumber: "PICO123456"  # Optional: target specific device
    
    # Option 2: Auto-discovery based on device type
    # autoDiscovery: true
    
    # Option 3: Device path discovery
    # devicePath:
    #   path: "/dev/ttyUSB*"
    #   permissions: "0666"
  
  # PKCS#11 configuration per device
  pkcs11:
    libraryPath: "/usr/local/lib/libsc-hsm-pkcs11.so"
    slotId: 0
    pinSecret:
      name: "pico-hsm-pin"
      key: "pin"
      namespace: "default"  # Optional: cross-namespace secret
    tokenLabel: "PicoHSM"     # Optional: specific token
  
  # Optional: target specific nodes
  nodeSelector:
    hsm-type: "pico"
  
  # Maximum number of devices to discover (default: 1)
  maxDevices: 1
---
apiVersion: hsm.j5t.io/v1alpha1
kind: HSMDevice
metadata:
  name: smartcard-hsm-discovery
  namespace: default
spec:
  deviceType: SmartCardHSM
  
  # Discovery configuration
  discovery:
    usb:
      vendorId: "04e6"
      productId: "5816"
  
  # PKCS#11 configuration
  pkcs11:
    libraryPath: "/usr/lib/opensc-pkcs11.so"
    slotId: 0
    pinSecret:
      name: "smartcard-hsm-pin"
      key: "pin"
    tokenLabel: "SmartCard-HSM"
  
  maxDevices: 3
---
apiVersion: hsm.j5t.io/v1alpha1
kind: HSMDevice
metadata:
  name: generic-hsm-path-discovery
  namespace: default
spec:
  deviceType: Generic
  
  # Discovery configuration
  discovery:
    # Device path discovery method
    devicePath:
      path: "/dev/sc-hsm*"
      permissions: "0666"
  
  # PKCS#11 configuration
  pkcs11:
    libraryPath: "/usr/lib/generic-pkcs11.so"
    slotId: 0
    pinSecret:
      name: "generic-hsm-pin"
      key: "pin"
    tokenLabel: "GenericHSM"
  
  maxDevices: 10
