apiVersion: hsm.j5t.io/v1alpha1
kind: HSMSecret
metadata:
  labels:
    app.kubernetes.io/name: hsm-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: hsmsecret-sample
  namespace: default
spec:
  # HSM path where the secret is stored
  hsmPath: "secrets/default/test-secret"
  
  # Name of the Kubernetes Secret to create (defaults to HSMSecret name if not specified)
  secretName: "database-credentials"
  
  # Enable automatic synchronization between HSM and Kubernetes Secret
  autoSync: true
  
  # Synchronization interval in seconds (default: 300)
  syncInterval: 60
  
  # Type of Kubernetes Secret to create (default: Opaque)
  secretType: Opaque
