apiVersion: hsm.j5t.io/v1alpha1
kind: HSMSecret
metadata:
  labels:
    app.kubernetes.io/name: hsm-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-database-secret
  namespace: production  # This HSMSecret is in the 'production' namespace
spec:
  # HSM path is automatically set to the metadata.name (app-database-secret)
  
  # ParentRef identifies which operator instance should handle this HSMSecret
  parentRef:
    name: controller-manager
    namespace: hsm-secrets-operator-system
  
  # Name of the Kubernetes Secret to create (defaults to HSMSecret name if not specified)
  secretName: "database-credentials"
  
  # Enable automatic synchronization between HSM and Kubernetes Secret
  autoSync: true
  
  # Synchronization interval in seconds (default: 300)
  syncInterval: 60
  
  # Type of Kubernetes Secret to create (default: Opaque)
  secretType: Opaque

---
# Another HSMSecret in a different namespace to demonstrate cross-namespace functionality
apiVersion: hsm.j5t.io/v1alpha1
kind: HSMSecret
metadata:
  labels:
    app.kubernetes.io/name: hsm-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: api-keys
  namespace: development  # This HSMSecret is in the 'development' namespace  
spec:
  # HSM path is automatically set to the metadata.name (api-keys)
  
  # ParentRef identifies which operator instance should handle this HSMSecret
  parentRef:
    name: controller-manager
    namespace: hsm-secrets-operator-system
  
  # Name of the Kubernetes Secret to create (defaults to HSMSecret name if not specified)
  secretName: "third-party-api-keys"
  
  # Enable automatic synchronization between HSM and Kubernetes Secret
  autoSync: true
  
  # Synchronization interval in seconds
  syncInterval: 30
  
  # Type of Kubernetes Secret to create
  secretType: Opaque