// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: hsm/v1/hsm.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common types
type HSMInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Label           string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Manufacturer    string                 `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model           string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	SerialNumber    string                 `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,5,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HSMInfo) Reset() {
	*x = HSMInfo{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HSMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSMInfo) ProtoMessage() {}

func (x *HSMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSMInfo.ProtoReflect.Descriptor instead.
func (*HSMInfo) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{0}
}

func (x *HSMInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *HSMInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *HSMInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HSMInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *HSMInfo) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

type SecretData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string][]byte      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretData) Reset() {
	*x = SecretData{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretData) ProtoMessage() {}

func (x *SecretData) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretData.ProtoReflect.Descriptor instead.
func (*SecretData) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{1}
}

func (x *SecretData) GetData() map[string][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SecretMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	DataType      string                 `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretMetadata) Reset() {
	*x = SecretMetadata{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMetadata) ProtoMessage() {}

func (x *SecretMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMetadata.ProtoReflect.Descriptor instead.
func (*SecretMetadata) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{2}
}

func (x *SecretMetadata) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SecretMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecretMetadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SecretMetadata) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SecretMetadata) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *SecretMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SecretMetadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Request/Response messages
type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{3}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HsmInfo       *HSMInfo               `protobuf:"bytes,1,opt,name=hsm_info,json=hsmInfo,proto3" json:"hsm_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{4}
}

func (x *GetInfoResponse) GetHsmInfo() *HSMInfo {
	if x != nil {
		return x.HsmInfo
	}
	return nil
}

type ReadSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSecretRequest) Reset() {
	*x = ReadSecretRequest{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSecretRequest) ProtoMessage() {}

func (x *ReadSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSecretRequest.ProtoReflect.Descriptor instead.
func (*ReadSecretRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{5}
}

func (x *ReadSecretRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretData    *SecretData            `protobuf:"bytes,1,opt,name=secret_data,json=secretData,proto3" json:"secret_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSecretResponse) Reset() {
	*x = ReadSecretResponse{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSecretResponse) ProtoMessage() {}

func (x *ReadSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSecretResponse.ProtoReflect.Descriptor instead.
func (*ReadSecretResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{6}
}

func (x *ReadSecretResponse) GetSecretData() *SecretData {
	if x != nil {
		return x.SecretData
	}
	return nil
}

type WriteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SecretData    *SecretData            `protobuf:"bytes,2,opt,name=secret_data,json=secretData,proto3" json:"secret_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSecretRequest) Reset() {
	*x = WriteSecretRequest{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSecretRequest) ProtoMessage() {}

func (x *WriteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSecretRequest.ProtoReflect.Descriptor instead.
func (*WriteSecretRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{7}
}

func (x *WriteSecretRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteSecretRequest) GetSecretData() *SecretData {
	if x != nil {
		return x.SecretData
	}
	return nil
}

type WriteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSecretResponse) Reset() {
	*x = WriteSecretResponse{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSecretResponse) ProtoMessage() {}

func (x *WriteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSecretResponse.ProtoReflect.Descriptor instead.
func (*WriteSecretResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{8}
}

type WriteSecretWithMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SecretData    *SecretData            `protobuf:"bytes,2,opt,name=secret_data,json=secretData,proto3" json:"secret_data,omitempty"`
	Metadata      *SecretMetadata        `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSecretWithMetadataRequest) Reset() {
	*x = WriteSecretWithMetadataRequest{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSecretWithMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSecretWithMetadataRequest) ProtoMessage() {}

func (x *WriteSecretWithMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSecretWithMetadataRequest.ProtoReflect.Descriptor instead.
func (*WriteSecretWithMetadataRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{9}
}

func (x *WriteSecretWithMetadataRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteSecretWithMetadataRequest) GetSecretData() *SecretData {
	if x != nil {
		return x.SecretData
	}
	return nil
}

func (x *WriteSecretWithMetadataRequest) GetMetadata() *SecretMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type WriteSecretWithMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSecretWithMetadataResponse) Reset() {
	*x = WriteSecretWithMetadataResponse{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSecretWithMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSecretWithMetadataResponse) ProtoMessage() {}

func (x *WriteSecretWithMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSecretWithMetadataResponse.ProtoReflect.Descriptor instead.
func (*WriteSecretWithMetadataResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{10}
}

type ReadMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMetadataRequest) Reset() {
	*x = ReadMetadataRequest{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMetadataRequest) ProtoMessage() {}

func (x *ReadMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMetadataRequest.ProtoReflect.Descriptor instead.
func (*ReadMetadataRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{11}
}

func (x *ReadMetadataRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *SecretMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMetadataResponse) Reset() {
	*x = ReadMetadataResponse{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMetadataResponse) ProtoMessage() {}

func (x *ReadMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMetadataResponse.ProtoReflect.Descriptor instead.
func (*ReadMetadataResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{12}
}

func (x *ReadMetadataResponse) GetMetadata() *SecretMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSecretRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{14}
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{15}
}

func (x *ListSecretsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{16}
}

func (x *ListSecretsResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type GetChecksumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChecksumRequest) Reset() {
	*x = GetChecksumRequest{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChecksumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChecksumRequest) ProtoMessage() {}

func (x *GetChecksumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChecksumRequest.ProtoReflect.Descriptor instead.
func (*GetChecksumRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{17}
}

func (x *GetChecksumRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetChecksumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      string                 `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChecksumResponse) Reset() {
	*x = GetChecksumResponse{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChecksumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChecksumResponse) ProtoMessage() {}

func (x *GetChecksumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChecksumResponse.ProtoReflect.Descriptor instead.
func (*GetChecksumResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{18}
}

func (x *GetChecksumResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type IsConnectedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConnectedRequest) Reset() {
	*x = IsConnectedRequest{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConnectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConnectedRequest) ProtoMessage() {}

func (x *IsConnectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConnectedRequest.ProtoReflect.Descriptor instead.
func (*IsConnectedRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{19}
}

type IsConnectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConnectedResponse) Reset() {
	*x = IsConnectedResponse{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConnectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConnectedResponse) ProtoMessage() {}

func (x *IsConnectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConnectedResponse.ProtoReflect.Descriptor instead.
func (*IsConnectedResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{20}
}

func (x *IsConnectedResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{21}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_hsm_v1_hsm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_hsm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_hsm_proto_rawDescGZIP(), []int{22}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hsm_v1_hsm_proto protoreflect.FileDescriptor

const file_hsm_v1_hsm_proto_rawDesc = "" +
	"\n" +
	"\x10hsm/v1/hsm.proto\x12\x06hsm.v1\"\xa9\x01\n" +
	"\aHSMInfo\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\"\n" +
	"\fmanufacturer\x18\x02 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12#\n" +
	"\rserial_number\x18\x04 \x01(\tR\fserialNumber\x12)\n" +
	"\x10firmware_version\x18\x05 \x01(\tR\x0ffirmwareVersion\"w\n" +
	"\n" +
	"SecretData\x120\n" +
	"\x04data\x18\x01 \x03(\v2\x1c.hsm.v1.SecretData.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xa3\x02\n" +
	"\x0eSecretMetadata\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x124\n" +
	"\x04tags\x18\x03 \x03(\v2 .hsm.v1.SecretMetadata.TagsEntryR\x04tags\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1b\n" +
	"\tdata_type\x18\x05 \x01(\tR\bdataType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eGetInfoRequest\"=\n" +
	"\x0fGetInfoResponse\x12*\n" +
	"\bhsm_info\x18\x01 \x01(\v2\x0f.hsm.v1.HSMInfoR\ahsmInfo\"'\n" +
	"\x11ReadSecretRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"I\n" +
	"\x12ReadSecretResponse\x123\n" +
	"\vsecret_data\x18\x01 \x01(\v2\x12.hsm.v1.SecretDataR\n" +
	"secretData\"]\n" +
	"\x12WriteSecretRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x123\n" +
	"\vsecret_data\x18\x02 \x01(\v2\x12.hsm.v1.SecretDataR\n" +
	"secretData\"\x15\n" +
	"\x13WriteSecretResponse\"\x9d\x01\n" +
	"\x1eWriteSecretWithMetadataRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x123\n" +
	"\vsecret_data\x18\x02 \x01(\v2\x12.hsm.v1.SecretDataR\n" +
	"secretData\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.hsm.v1.SecretMetadataR\bmetadata\"!\n" +
	"\x1fWriteSecretWithMetadataResponse\")\n" +
	"\x13ReadMetadataRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"J\n" +
	"\x14ReadMetadataResponse\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.hsm.v1.SecretMetadataR\bmetadata\")\n" +
	"\x13DeleteSecretRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x16\n" +
	"\x14DeleteSecretResponse\",\n" +
	"\x12ListSecretsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"+\n" +
	"\x13ListSecretsResponse\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"(\n" +
	"\x12GetChecksumRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"1\n" +
	"\x13GetChecksumResponse\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\tR\bchecksum\"\x14\n" +
	"\x12IsConnectedRequest\"3\n" +
	"\x13IsConnectedResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe6\x05\n" +
	"\bHSMAgent\x12:\n" +
	"\aGetInfo\x12\x16.hsm.v1.GetInfoRequest\x1a\x17.hsm.v1.GetInfoResponse\x12C\n" +
	"\n" +
	"ReadSecret\x12\x19.hsm.v1.ReadSecretRequest\x1a\x1a.hsm.v1.ReadSecretResponse\x12F\n" +
	"\vWriteSecret\x12\x1a.hsm.v1.WriteSecretRequest\x1a\x1b.hsm.v1.WriteSecretResponse\x12j\n" +
	"\x17WriteSecretWithMetadata\x12&.hsm.v1.WriteSecretWithMetadataRequest\x1a'.hsm.v1.WriteSecretWithMetadataResponse\x12I\n" +
	"\fReadMetadata\x12\x1b.hsm.v1.ReadMetadataRequest\x1a\x1c.hsm.v1.ReadMetadataResponse\x12I\n" +
	"\fDeleteSecret\x12\x1b.hsm.v1.DeleteSecretRequest\x1a\x1c.hsm.v1.DeleteSecretResponse\x12F\n" +
	"\vListSecrets\x12\x1a.hsm.v1.ListSecretsRequest\x1a\x1b.hsm.v1.ListSecretsResponse\x12F\n" +
	"\vGetChecksum\x12\x1a.hsm.v1.GetChecksumRequest\x1a\x1b.hsm.v1.GetChecksumResponse\x12F\n" +
	"\vIsConnected\x12\x1a.hsm.v1.IsConnectedRequest\x1a\x1b.hsm.v1.IsConnectedResponse\x127\n" +
	"\x06Health\x12\x15.hsm.v1.HealthRequest\x1a\x16.hsm.v1.HealthResponseB>Z<github.com/evanjarrett/hsm-secrets-operator/api/proto/hsm/v1b\x06proto3"

var (
	file_hsm_v1_hsm_proto_rawDescOnce sync.Once
	file_hsm_v1_hsm_proto_rawDescData []byte
)

func file_hsm_v1_hsm_proto_rawDescGZIP() []byte {
	file_hsm_v1_hsm_proto_rawDescOnce.Do(func() {
		file_hsm_v1_hsm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hsm_v1_hsm_proto_rawDesc), len(file_hsm_v1_hsm_proto_rawDesc)))
	})
	return file_hsm_v1_hsm_proto_rawDescData
}

var file_hsm_v1_hsm_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_hsm_v1_hsm_proto_goTypes = []any{
	(*HSMInfo)(nil),                         // 0: hsm.v1.HSMInfo
	(*SecretData)(nil),                      // 1: hsm.v1.SecretData
	(*SecretMetadata)(nil),                  // 2: hsm.v1.SecretMetadata
	(*GetInfoRequest)(nil),                  // 3: hsm.v1.GetInfoRequest
	(*GetInfoResponse)(nil),                 // 4: hsm.v1.GetInfoResponse
	(*ReadSecretRequest)(nil),               // 5: hsm.v1.ReadSecretRequest
	(*ReadSecretResponse)(nil),              // 6: hsm.v1.ReadSecretResponse
	(*WriteSecretRequest)(nil),              // 7: hsm.v1.WriteSecretRequest
	(*WriteSecretResponse)(nil),             // 8: hsm.v1.WriteSecretResponse
	(*WriteSecretWithMetadataRequest)(nil),  // 9: hsm.v1.WriteSecretWithMetadataRequest
	(*WriteSecretWithMetadataResponse)(nil), // 10: hsm.v1.WriteSecretWithMetadataResponse
	(*ReadMetadataRequest)(nil),             // 11: hsm.v1.ReadMetadataRequest
	(*ReadMetadataResponse)(nil),            // 12: hsm.v1.ReadMetadataResponse
	(*DeleteSecretRequest)(nil),             // 13: hsm.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),            // 14: hsm.v1.DeleteSecretResponse
	(*ListSecretsRequest)(nil),              // 15: hsm.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),             // 16: hsm.v1.ListSecretsResponse
	(*GetChecksumRequest)(nil),              // 17: hsm.v1.GetChecksumRequest
	(*GetChecksumResponse)(nil),             // 18: hsm.v1.GetChecksumResponse
	(*IsConnectedRequest)(nil),              // 19: hsm.v1.IsConnectedRequest
	(*IsConnectedResponse)(nil),             // 20: hsm.v1.IsConnectedResponse
	(*HealthRequest)(nil),                   // 21: hsm.v1.HealthRequest
	(*HealthResponse)(nil),                  // 22: hsm.v1.HealthResponse
	nil,                                     // 23: hsm.v1.SecretData.DataEntry
	nil,                                     // 24: hsm.v1.SecretMetadata.TagsEntry
}
var file_hsm_v1_hsm_proto_depIdxs = []int32{
	23, // 0: hsm.v1.SecretData.data:type_name -> hsm.v1.SecretData.DataEntry
	24, // 1: hsm.v1.SecretMetadata.tags:type_name -> hsm.v1.SecretMetadata.TagsEntry
	0,  // 2: hsm.v1.GetInfoResponse.hsm_info:type_name -> hsm.v1.HSMInfo
	1,  // 3: hsm.v1.ReadSecretResponse.secret_data:type_name -> hsm.v1.SecretData
	1,  // 4: hsm.v1.WriteSecretRequest.secret_data:type_name -> hsm.v1.SecretData
	1,  // 5: hsm.v1.WriteSecretWithMetadataRequest.secret_data:type_name -> hsm.v1.SecretData
	2,  // 6: hsm.v1.WriteSecretWithMetadataRequest.metadata:type_name -> hsm.v1.SecretMetadata
	2,  // 7: hsm.v1.ReadMetadataResponse.metadata:type_name -> hsm.v1.SecretMetadata
	3,  // 8: hsm.v1.HSMAgent.GetInfo:input_type -> hsm.v1.GetInfoRequest
	5,  // 9: hsm.v1.HSMAgent.ReadSecret:input_type -> hsm.v1.ReadSecretRequest
	7,  // 10: hsm.v1.HSMAgent.WriteSecret:input_type -> hsm.v1.WriteSecretRequest
	9,  // 11: hsm.v1.HSMAgent.WriteSecretWithMetadata:input_type -> hsm.v1.WriteSecretWithMetadataRequest
	11, // 12: hsm.v1.HSMAgent.ReadMetadata:input_type -> hsm.v1.ReadMetadataRequest
	13, // 13: hsm.v1.HSMAgent.DeleteSecret:input_type -> hsm.v1.DeleteSecretRequest
	15, // 14: hsm.v1.HSMAgent.ListSecrets:input_type -> hsm.v1.ListSecretsRequest
	17, // 15: hsm.v1.HSMAgent.GetChecksum:input_type -> hsm.v1.GetChecksumRequest
	19, // 16: hsm.v1.HSMAgent.IsConnected:input_type -> hsm.v1.IsConnectedRequest
	21, // 17: hsm.v1.HSMAgent.Health:input_type -> hsm.v1.HealthRequest
	4,  // 18: hsm.v1.HSMAgent.GetInfo:output_type -> hsm.v1.GetInfoResponse
	6,  // 19: hsm.v1.HSMAgent.ReadSecret:output_type -> hsm.v1.ReadSecretResponse
	8,  // 20: hsm.v1.HSMAgent.WriteSecret:output_type -> hsm.v1.WriteSecretResponse
	10, // 21: hsm.v1.HSMAgent.WriteSecretWithMetadata:output_type -> hsm.v1.WriteSecretWithMetadataResponse
	12, // 22: hsm.v1.HSMAgent.ReadMetadata:output_type -> hsm.v1.ReadMetadataResponse
	14, // 23: hsm.v1.HSMAgent.DeleteSecret:output_type -> hsm.v1.DeleteSecretResponse
	16, // 24: hsm.v1.HSMAgent.ListSecrets:output_type -> hsm.v1.ListSecretsResponse
	18, // 25: hsm.v1.HSMAgent.GetChecksum:output_type -> hsm.v1.GetChecksumResponse
	20, // 26: hsm.v1.HSMAgent.IsConnected:output_type -> hsm.v1.IsConnectedResponse
	22, // 27: hsm.v1.HSMAgent.Health:output_type -> hsm.v1.HealthResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_hsm_v1_hsm_proto_init() }
func file_hsm_v1_hsm_proto_init() {
	if File_hsm_v1_hsm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hsm_v1_hsm_proto_rawDesc), len(file_hsm_v1_hsm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hsm_v1_hsm_proto_goTypes,
		DependencyIndexes: file_hsm_v1_hsm_proto_depIdxs,
		MessageInfos:      file_hsm_v1_hsm_proto_msgTypes,
	}.Build()
	File_hsm_v1_hsm_proto = out.File
	file_hsm_v1_hsm_proto_goTypes = nil
	file_hsm_v1_hsm_proto_depIdxs = nil
}
